# Generated by Django 5.2.3 on 2025-06-23 19:53

import django.db.models.deletion
import forum.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fac', models.CharField(max_length=100)),
                ('code_fac', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeDeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=100)),
                ('statut_groupe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Nom')),
                ('profile_type', models.CharField(choices=[('etudiant', 'Étudiant'), ('professeur', 'Professeur'), ('admin', 'Administrateur')], default='etudiant', help_text="Rôle principal de l'utilisateur", max_length=20, verbose_name='Type de profil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Personnel')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(default=forum.models.generate_matricule, max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='numéro matricule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
                ('id_faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='forum.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrib', models.CharField(choices=[('texte', 'Texte'), ('fichier', 'Fichier')], max_length=20)),
                ('contenu', models.TextField()),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='contributions/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='forum.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_com', models.TextField()),
                ('date_com', models.DateTimeField(auto_now_add=True)),
                ('id_contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='forum.contribution')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='forum.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prof_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_cours', models.CharField(max_length=100)),
                ('code_cours', models.CharField(max_length=20, unique=True)),
                ('id_professeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='forum.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_promo', models.CharField(max_length=50)),
                ('code_promo', models.CharField(max_length=20, unique=True)),
                ('id_faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='forum.faculte')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='forum.promotion'),
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_fichier_rapport', models.URLField(verbose_name='URL du rapport')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='forum.groupedetravail')),
            ],
        ),
        migrations.CreateModel(
            name='SujetDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_sujet', models.CharField(max_length=200, verbose_name='Titre du Sujet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date limite')),
                ('description', models.TextField(verbose_name='Description du sujet')),
                ('id_createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='forum.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_tp', models.CharField(max_length=200, verbose_name='Titre du TP')),
                ('date_limit', models.DateTimeField(verbose_name='Date limite')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description du TP')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='forum.cours')),
            ],
        ),
        migrations.AddField(
            model_name='groupedetravail',
            name='id_travail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='forum.travail'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='id_travail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='forum.travail'),
        ),
        migrations.CreateModel(
            name='EtudiantGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_chef', models.BooleanField(default=False, verbose_name='Chef de groupe')),
                ('date_rejoindre', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.etudiant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.groupedetravail')),
            ],
            options={
                'unique_together': {('etudiant', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reaction', models.CharField(choices=[('like', 'J’aime'), ('dislike', 'Je n’aime pas')], max_length=10)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.contribution')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'contribution')},
            },
        ),
        migrations.CreateModel(
            name='rejoundregroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('id_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.etudiant')),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.groupedetravail')),
            ],
            options={
                'unique_together': {('id_etudiant', 'id_groupe')},
            },
        ),
    ]
