# Generated by Django 5.2.3 on 2025-06-24 15:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_travail_id_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupedetravail',
            name='capacite_max',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='professeur',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='spécialité'),
        ),
        migrations.AddField(
            model_name='travail',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travaux_crees', to='forum.professeur'),
        ),
        migrations.AddField(
            model_name='travail',
            name='date_post',
            field=models.DateField(default=datetime.date.today, verbose_name='date de publication'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contenu',
            field=models.TextField(blank=True, help_text='Contenu de la contribution (texte ou fichier)', null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='type_contrib',
            field=models.CharField(choices=[('texte', 'Texte'), ('fichier', 'Fichier')], default='texte', max_length=20),
        ),
        migrations.RemoveField(
            model_name='cours',
            name='id_professeur',
        ),
        migrations.AlterField(
            model_name='etudiantgroupe',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_rejoins', to='forum.etudiant'),
        ),
        migrations.AlterField(
            model_name='groupedetravail',
            name='statut_groupe',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('en_attente', 'En attente'), ('pret', 'Prêt')], default='ouvert', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='groupedetravail',
            unique_together={('nom_groupe', 'id_travail')},
        ),
        migrations.AddField(
            model_name='cours',
            name='id_professeur',
            field=models.ManyToManyField(related_name='cours_enseignes', to='forum.professeur'),
        ),
    ]
