# Generated by Django 5.2.3 on 2025-06-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_groupedetravail_capacite_max_professeur_specialite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description du cours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='id_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='forum.promotion'),
        ),
    ]
